version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - db

  frontend:
    build: ./frontend/
    volumes:
      - static:/static
    command: sh -c "npm run build && cp -r /app/build/. /static/"
    depends_on:
      - backend

  gateway:
    build: ./nginx/
    ports:
      - "9000:80"
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
