version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/app/staticfiles  
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:9090 kittygram_backend.wsgi"

  frontend:
    build: ./frontend/
    volumes:
      - static:/app/build
    depends_on:
      - backend

  gateway:
    build: ./nginx/
    ports:
      - "9000:80"
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend