# скрываем версию nginx
server_tokens off;

# Определяем группу серверов backend
upstream backend {
    server backend:9090;
}

# Настройки сервера
server {
  listen 80;
  client_max_body_size 10M;  # Максимальный размер загружаемого файла
  index index.html;  # Индексный файл по умолчанию

  # Раздача статических файлов
  location /static/ {
    alias /staticfiles/;  # alias - физический путь к файлам
  }

  # Раздача медиа файлов
  location /media/ {
    alias /media/;
  }

  # Проксирование API запросов на backend
  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend/api/;
  }

  
    # Проксирование запросов к админке Djangolocation /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend/admin/;
  }

  # Все остальные запросы - отдаем фронтенд
  location / {
    alias /staticfiles/;  # Ищем файлы в папке со статикой
    try_files $uri $uri/ /index.html;  # Если файл не найден - отдаем index.html
  }
}